const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
const UPDATE_CATEGORY = "UPDATE_CATEGORY";
const ADD_CATEGORY = "ADD_CATEGORY";
const DELETE_CATEGORY = "DELETE_CATEGORY";

const GET_ALL_POST = "GET_ALL_POST";
const UPDATE_POST = "UPDATE_POST";
const ADD_POST = "ADD_POST";
const DELETE_POST = "DELETE_POST";

const GET_ALL_USER = "GET_ALL_USER";
const UPDATE_USER = "UPDATE_USER";
const ADD_USER = "ADD_USER";
const DELETE_USER = "DELETE_USER";
const SIGN_IN = "SIGN_IN";

export {
  GET_ALL_CATEGORY,
  UPDATE_CATEGORY,
  ADD_CATEGORY,
  DELETE_CATEGORY,
  GET_ALL_POST,
  UPDATE_POST,
  ADD_POST,
  DELETE_POST,
  GET_ALL_USER,
  UPDATE_USER,
  ADD_USER,
  DELETE_USER,
  SIGN_IN,
};
